services:
  service-anonymous:
    system_user: undefined
    acl: []

  service-hashtag:
    system_user: my-custom-user
    acl:
      - '#'

  service-standard:
    system_user: root
    acl:
      - 'random.acl.*'
      - 'weird.random.#'
      - 'another.random.read'

policies:
  policy-empty: []
  policy-standard:
    - 'random.acl.*'
    - 'weird.random.#'
    - 'another.random.read'
