debug: True
foreground: True

db_uri: postgresql://asterisk:proformatique@postgres:5432

amqp:
  uri: amqp://guest:guest@rabbitmq:5672/

service_discovery:
  enabled: false

token_cleanup_interval: 2.0

init_key_filename: /tmp/init.key  # bootstrap setup

enabled_http_plugins:
  init: True  # bootstrap setup
  users: True

enabled_backend_plugins:
  wazo_user: True
